title: IdeoGuardian's Portfolio
author: Ideo_Guardian
email: your-email@domain.com
description: Full Stack Web Developer & Software Engineer

baseurl: "" # Leave empty if this is your main site
url: "https://ideoguardian.github.io"

# Build settings
theme: jekyll-theme-minimal
show_downloads: false
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links (optional)
github_username: IdeoGuardian
twitter_username: your-twitter-handle
