title: My Blog
description: Welcome to my personal blog
author: Your Name
url: "https://ideoguardian.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
