title: IdeoGuardian Project
description: Welcome to IdeoGuardian Project
author: IdeoGuardian
url: "https://ideoguardian.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:title/
