title: Identity Guardian Project
description: Welcome to Identity Guardian Project
author: Identity Guardian
url: "https://ideoguardian.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:title/
