title: My Blog
author: Your Name
email: your-email@example.com
description: >- 
  Write a description about your blog here.

baseurl: "" # Leave empty if this is your main site
url: "https://ideoguardian.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links (optional)
github_username: IdeoGuardian
twitter_username: your-twitter-handle
